### ISSUE TITLE
Open in new tab resolves URL relative to extension

### ISSUE THREAD

**Issue by Pharb** [gopasspw/gopassbridge#106]
<img width="312" alt="screen shot 2019-01-06 at 17 44 43" src="https://user-images.githubusercontent.com/7095678/50739110-ae391f80-11db-11e9-8d96-3a0e70557898.png">

Using non-absolute URLs (like github.com instead of https://github.com) will open tabs with URLs like `moz-extension://c5b78afa-2856-064c-b444-d70b2e955f89/github.com` or `chrome-extension://nmlipgjeejicjaapphmmonmlfkecmnoi/github.com`.

Can be reproduced in Chrome and Firefox with gopassbridge v0.5.0.

**Comment by martinhoefling** [comment]
Would an acceptable solution be to prepend https:// in case that the url does not start with a protocol?

**Comment by Pharb** [comment]
@martinhoefling Yes, I think that would be acceptable.

**Comment by martinhoefling** [comment]
@Pharb can you still reproduce the issue?
I have an entry like:
```
somepassword
url: github.com
```
but it does not show it as url (as expected) due to the regexp.
