### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by kron4eg** [gopasspw/gopassbridge#110]
How hard it would be to make gopassbridge also work on Safari?

**Comment by martinhoefling** [comment]
Safari doesn’t support the web extension standard, that Firefox, Chrome, Opera and Edge support. Further, I am also not sure if native messaging is supported by Safari.

So to answer your question: probably yes.

**Comment by dertuxmalwieder** [comment]
I'd suggest to reopen this, as recent Safari versions both support the web extension standard [and native messaging.](https://developer.apple.com/documentation/safariservices/safari_web_extensions/messaging_between_the_app_and_javascript_in_a_safari_web_extension)
