### ISSUE TITLE
Ignore some fields in the detailed view

### ISSUE THREAD

**Issue by thatlittleboy** [gopasspw/gopassbridge#114]
I store my 2FA backup/recovery codes in the gpg files, a mockup of what my typical file looks like:

```
a_long_random_password
url: www.github.com
email: abc@gmail.com
otpauth://totp//...

recovery codes:
abcde-12345
fghij-67890
zyxwv-05432
```

Then opening up the detailed view from gopassbridge within Firefox shows:

**:**
**abcde-12345:**
**current-totp:** 919191
**email:** abc@gmail.com
**fghij-67890:**
**otpauth:** //totp//...
**recovery codes:**
**url:** www.github.com
**zyxwv-05432:**

So, a couple of issues:
- Empty lines are not ignored, so we get spurious lines in the detailed view like "**:**" (line 1)
- I place 1 recovery code per line, but in the detailed view, they get read in as keys with no corresponding values; Plus they are ordered alphabetically in the display which means they appear all over the place (messy)
- otpauth gets read in as a key-value as well, which doesn't make sense at all.
- "**recovery codes**" that I used as a "header" for my codes gets parsed as an entry by itself, which is less than ideal as well.

Is there a way to tell gopassbridge to ignore some lines in my file, and **not** have them appear in the detailed view? 
The benefits:
1. It avoids this messy output (so it looks better aesthetically),
2. makes it easier to find the field that I am actually looking for (95% of the time, it is to get the TOTP), and 
3. (most importantly!) avoids revealing my recovery codes on my screen everytime I want to access my TOTP during login time. 

Thus, ideally, what I wish to see in the detailed view instead:

**current-totp:** 919191
**email:** abc@gmail.com
**url:** www.github.com

i.e., no recovery codes, no headers, no empty lines. The way I see this being implemented is to perhaps not parse any lines without valid key-value syntax (or have empty values), and to explicitly ignore lines that begin with `otpauth`.
Either that, or give explicit control to the user to decide which field to show/ignore via the YAML syntax. [This](https://github.com/gopasspw/gopassbridge/issues/34#issuecomment-388464045) comes to mind.

I am using Gopass 0.5.1 on Firefox Quantum 64.0.4

Cheers!

**Comment by martinhoefling** [comment]
Would skipping keys with empty values help? This makes no sense to me in general, right? Alternatively, we could introduce a setting for keys to filter out. What do you think is the best solution here?

**Comment by thatlittleboy** [comment]
1. It would, IMHO. Can you suggest in what alternative scenarios would a key _without_ value be required / useful for the user? The other way to look at it is that the UI, as it is currently designed, very much suggests a key-value syntax only (the key being bolded, and the value coming after the colon). Furthermore, it is set up such that the user clicks on the value to copy it, and never the key. So to me, there isn't much point in keeping an entry with a key and no value. 

2. The settings approach could work; I think the most elegant way is to enforce via the syntax and leave it to the user to decide which keys to filter out, as per the earlier discussion in #34. This would address all my issues with the current implementation. 

The issue we have here (as I see it) is that these password files are essentially just text files, so anything goes; except the first line which is always the password. But gopassbridge enforces/assumes a certain structure to the file contents (i.e., key-value) when parsing for the detailed view. 
So I certainly think that an option (in whatever form you deem fit) should exist to exclude the lines that don't conform to the kv syntax.

p.s. to be clear, the main issue that I have here is that my recovery codes are showing up in plain sight when I open up the detailed view; so I am a bit apprehensive to login to websites with 2FA using gopassbridge in public. The rest of my "complaints" (messy output, empty lines etc.) are just mild annoyances, and the suggestion to exclude certain lines in the password file is just 1 potential solution to the problem.

**Comment by martinhoefling** [comment]
Concerning 1. I don't see a scenario, so let's implement this first. Not sure about 2. yet. A filter setting can be set in gopassbridge but an alternative structure requires changes in the gopass jsonapi code.

**Comment by Pharb** [comment]
@thatlittleboy Thanks for raising this issue. Currently is relatively little documented how structured data in gopass entries works and gopassbridge also does not do a good job in showing that in the UI.

For now I would recommend following this example: https://github.com/gopasspw/gopass/blob/master/docs/features.md#directly-edit-structured-secrets-aka-yaml-support

To now show an entry you can comment the line in YAML with a "#" at the beginning of the line. Don't forget the "---" to separate the password of from the YAML part of the gopass entry. You can use `gopass edit <secret_name>` to modify it.

This should work for your example:
```yaml
a_long_random_password
---
url: www.github.com
email: abc@gmail.com
totp: otpauth://totp//...

# recovery codes:
# abcde-12345
# fghij-67890
# zyxwv-05432
```

With the next release of gopassbridge there should also be better handling of empty values (#115) and for using more complex YAML structures (#119).

Further I think we could also implement a "hide keys" option, which by default should probably hide the `totp` entry from the detail view. Maybe it is also simple to add a small "hide" icon to keys in the detail view which would then add the key name to the list of hidden keys in the options.

**Comment by martinhoefling** [comment]
@Pharb : both ways sound good to me. A FE softcoded list of fieldnames is probably more flexible and not much more effort.
