### ISSUE TITLE
"Addon appears to be corrupt" when trying to install in firefox dev

### ISSUE THREAD

**Issue by kolaente** [gopasspw/gopassbridge#118]
Hey there,

when I try to install the addon in Firefox (from [the addons store](https://addons.mozilla.org/en-US/firefox/addon/gopass-bridge/?src=search), I get this error message instead:

![image](https://user-images.githubusercontent.com/13721712/60813055-27b5c880-a193-11e9-8a53-d6d90ab75ae0.png)

Is that a problem with Firefox or Mozilla or my setup?
I'm running Firefox Developer Edition 66.0b7 on a fresh install of nixos 19.03.

**Comment by martinhoefling** [comment]
Can not reproduce with latest Firefox developer edition on Mac. Can you try an up to date version?

**Comment by kolaente** [comment]
Hm looks like it works in the latest (68.0b12) version, strange.

**Comment by martinhoefling** [comment]
Maybe the older version hasn’t upgraded the root certificate? I remember Mozilla messed this up a while ago. 

Closing the issue as I don’t see what we can do about it (we’re using standard tooling and signing happens on Mozilla side)
