### ISSUE TITLE
Wrong path to secret on Windows with Firefox

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopassbridge#122]
I am running gopass on windows and it seems like the path separators are wrong when using substores. This leads to passwords not being accessible.

![step1](https://user-images.githubusercontent.com/2115696/63113443-8de6f580-bf60-11e9-947a-3aa50eb0ae4d.png)

![step2](https://user-images.githubusercontent.com/2115696/63113449-90e1e600-bf60-11e9-854b-876026a3dc3f.png)

**Comment by Pharb** [comment]
Hello @AuspeXeu,

Thank you for raising this issue. It definitely looks like a bug in either gopassbridge or gopass.

As I currently do not run gopassbridge on Windows, I am unable to reproduce this issue at the moment, but I will try to spend some time on that in the future.

It would be much appreciated, if somebody else could reproduce this and find the places in the code where these paths are generated. For gopassbridge, this should be somewhere around here: https://github.com/gopasspw/gopassbridge/blob/master/web-extension/search.js#L101

We are open for pull requests that would solve this issue.

**Comment by AuspeXeu** [comment]
Hey @Pharb,
I just fiddled around a bit with the code and everything works fine with a small cleanup step for gopass' response. I'll create a PR for this now.

**Comment by AuspeXeu** [comment]
Have done some more digging, and this is indeed a problem of gopass' JSON api.

**Comment by Pharb** [comment]
I'll try to get the next bug-fix version v0.6.3 out soon, currently we are waiting for the Chrome Store to review our latest release. Shouldn't take longer than a few days I hope.

**Comment by Pharb** [comment]
These changes are included in v0.7, which is available for Firefox now (Chrome release is pending review again...).
