### ISSUE TITLE
Error message when native messaging is not enabled is not helpful

### ISSUE THREAD

**Issue by corneliusweig** [gopasspw/gopassbridge#139]
I was struggling when moving my setup to a new browser. Suddenly, gopassbridge would not work anymore and just say that 'native messaging' was not enabled (or similar). I find this not very helpful because it does not include a pointer how to fix this (or at least where it's documented).

Ideally, I would expect this information in one of the following places (or both):

* when clicking on the gopass icon: instead or beside the current error message about malfunctioning native messaging
* some setup guidelines in the plugin settings page.

**Comment by martinhoefling** [comment]
@corneliusweig , can you specify which message you get on which browser / version / gopassbridge plugin version? I checked locally and on firefox , I get a hint with a link to the setup documentation. The additional link is triggered by:
```
    'Access to the specified native messaging host is forbidden',
    'Attempt to postMessage on disconnected port',
```
at the moment.

**Comment by corneliusweig** [comment]
@martinhoefling I'm using gopassbridge 0.6.0 on Chrome 80. This is all I see and the item is not clickable:
![Screenshot from 2020-02-22 13-28-59](https://user-images.githubusercontent.com/22861411/75092437-c0108a00-5577-11ea-9408-82c1bd8b94fd.png)

**Comment by martinhoefling** [comment]
I was able to reproduce the issue with chrome 80. Adding the string helps:
