### ISSUE TITLE
no results for [blah blah dot com] on Windows

### ISSUE THREAD

**Issue by NuLL3rr0r** [gopasspw/gopassbridge#142]
Well, on Windows no matter which browser I am using (Firefox, Chromium, or Chrome) I always get the no results for prompt:

![gopass-001](https://user-images.githubusercontent.com/2454895/75141636-aeeb8880-56f1-11ea-9723-891726c84507.png)

But, when I start typing the domain or user names, it shows me the entries and let me login:

![gopass-002](https://user-images.githubusercontent.com/2454895/75141644-b448d300-56f1-11ea-8493-5539417898ae.png)

On Linux I don't have this issue. Whenever I click on gopassbridge icon the user names for that domain are ready to be chosen.

**Comment by Pharb** [comment]
Thanks for the report @NuLL3rr0r.

From your description it might be similar to #122. There is currently a PR #123 being worked to hopefully improve the situation on Windows a bit.

**Comment by NuLL3rr0r** [comment]
Thank you for the info.

**Comment by AuspeXeu** [comment]
@Pharb when do you think we can expect this to land on firefox? :)

**Comment by Pharb** [comment]
@AuspeXeu We are currently waiting for the latest released version 0.6.2 to be "reviewed" by Google to appear in the Chrome store. When this is done, I would immediately roll-out the next version including this fix.

Sadly there seems to be no way to speedup the Google review process, so it could take a few more days or more.

**Comment by Pharb** [comment]
@NuLL3rr0r A new version v0.7.0 was released and available for Firefox today. This includes some improvements for path handling on Windows.

The Chrome release of v0.7.0 is still pending review, so it might take a few days to show up in the Chrome store.

**Comment by NuLL3rr0r** [comment]
@Pharb thank you so much for letting me know. I will try it out and let you know if I still have issues with it.

**Comment by Pharb** [comment]
Let's close this for now, if there are still issues, please let me know.

**Comment by martinhoefling** [comment]
@NuLL3rr0r , I have checked the issue and it is not resolved with gopassbridge 0.7 but for me it works with gopass from master (which will be released soon).

**Comment by NuLL3rr0r** [comment]
Thank you so much. I am looking forward to it.
