### ISSUE TITLE
Core dump with vivaldi 3.0.1874.23-1

### ISSUE THREAD

**Issue by krisko** [gopasspw/gopassbridge#150]
Hi,
I've updated vivaldi on Arch to 3.0.1874.23-1 and the browser is crashing when I try to use gopassbridge.
In console I can see messages:
```
../../chromium/third_party/re2/src/re2/re2.cc:194: Error parsing '^https?:\/\/([0-9a-z\-]+\.)?(animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime...': invalid perl operator: (?!
../../chromium/third_party/re2/src/re2/re2.cc:799: Invalid RE2: invalid perl operator: (?!
gpg-agent: a gpg-agent is already running - not starting a new one
zsh: trace trap (core dumped)  vivaldi-stable
```

**Comment by martinhoefling** [comment]
@krisko, sorry, I have no idea if/how the regexp error is related to gopassbridge. Which console do you refer to? The browser console? Can you explain which site you're navigating to and where the anime* strings are coming from?

**Comment by Pharb** [comment]
I strongly suspect the perl/regex errors are from a different browser extension, unrelated to gopassbridge.

This line seems relevant: `a gpg-agent is already running - not starting a new one`

@krisko Could you also give us more details about your gpg setup? Maybe you can find some clues here: https://wiki.archlinux.org/index.php/GnuPG#Reload_the_agent

You can try to force stop the gpg-agent `killall gpg-agent` and restart it with `gpg-agent --daemon`.

Another common issue could be related to your `pinentry`, which is the program that is used to enter your GPG key passphrase. This can also be very specific to your operating system: https://wiki.archlinux.org/index.php/GnuPG#pinentry

**Comment by krisko** [comment]
yes, you were right. Restarting the gpg-agent solved the issue.

Thanks!
