### ISSUE TITLE
Question: Vulnerability against Port-Scanning-Websites

### ISSUE THREAD

**Issue by jerger** [gopasspw/gopassbridge#153]
If I know right, gopassbridge uses a localhost-webservice to talk to gopass. 

As I read https://nullsweep.com/why-is-this-website-port-scanning-me/
I asked myself whether portscanners can detect my localhost gopass webservice and how this connection is secured against evil websites ...

Do you have some kind of threat-analysis done? Is there sth. I can read about your considerations?

**Comment by martinhoefling** [comment]
gopassbridge is not vulnerable against portscanning as it is not opening any ports on gopass side. It's purely using [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to communicate with gopass.

**Comment by jerger** [comment]
cool :-)
