### ISSUE TITLE
gopassbridge cancels requests when loosing focus to the Pinentry window

### ISSUE THREAD

**Issue by leogott** [gopasspw/gopassbridge#154]
Several actions I can take within gopassbridge cause it to ask for a secret, but cancel the request shortly after.

Gopassbridge appears to request a secret, when clicking on "show details" for a result, but when the browser looses focus to the gpg Pinentry window, the gopassbridge popup disappears and the Pinentry window does shortly after.

The same happens sometimes* when the url matches an entry, a text-entry-field is active (has a blinking cursor) and I click on the gopassbridge icon.

The same happens sometimes* under the same conditions, when I hover over an entry in the results list.

When I click on an entry and not on one of the buttons, I frequently get a "Failed to get secret: failed to decrypt" notification from gopassbridge.

I encounter these issues most often, when on a login page that has the email and password fields split over two pages. (eg. signin.ebay.de)

I'm not sure if all of these are the same issue, but I couldn't narrow them down more on my own, as the gpg Pinentry window is quite slow to appear on my system (up to 10s).

This issue is similar to #112 , but seemed different enough that I opened a new one.

Versions:
Windows 10 Pro (64 bit)
Firefox Beta 77.0 (64 bit)
gopassbridge 0.7.0
installed via scoop:
  gopass 1.8.6
  gpg 2.2.20

**Comment by Pharb** [comment]
Thanks for the detailed report @leogott.

I understand your frustration that in some cases the Pinentry windows from your GPG setup causes the gopassbridge popup to disappear.

Sadly I suspect that this behaviour strongly depends on the interactions between Firefox, your gpg-agent and the Pinentry program and there is little that the gopassbridge browser extension can do to make those behave better.

Can you please try to find your `gpg-agent.conf` file and include it here?
Usually there is a cache setting, which determines how long gpg-agent will remember your passphrase in memory before asking again (e.g. `default-cache-ttl`).

Personally it often works for me to open the gopassbridge popup a second time, and using the cached PIN or passphrase.

**Comment by leogott** [comment]
So it looks like there was no gpg config file?
`PS C:\Users\[me]> gpgconf --list-config`
`gpgconf: can not open global config file 'C:\Users\[me]\scoop\apps\gpg\current\etc\gnupg\gpgconf.conf': No such file or directory`

First unlocking the password-store from the powershell before using gopassbridge is what I did before, and it appears to be a reliable workaround.

**Comment by leogott** [comment]
I tried again with an **older** version of Firefox (Release 76.0.1 64 Bit) and didn't get the issue.

In this older version, after some very superficial testing, it appears that the Browser loosing focus *doesn't* mess with gopassbridge.

**Comment by leogott** [comment]
Confirmed. On my system, gopassbridge behaves as expected after updating gopass from 1.8.6 to 1.9.2
