### ISSUE TITLE
Shortcut doesn't work when you are focus on inputbox

### ISSUE THREAD

**Issue by Bersam** [gopasspw/gopassbridge#156]
Hi,

So I notice strange behavior with default shortcut that gopassbridge has (and It's not possible to change) and basically whenever I try to use it and focus is on an inputbox, it types `u` instead of running the shortcut. 
I'm using EuKey layout and this issue might be related to my keyboard layout, still, I think it's good to have the option to change it.

**Comment by martinhoefling** [comment]
Have you tried to change the shortcut? The Readme contains a section “Change default shortcut”.

**Comment by Bersam** [comment]
@martinhoefling ah awesome! changing it fixed the problem, I was looking in wrong place.
