### ISSUE TITLE
Install from source instructions unclear.

### ISSUE THREAD

**Issue by iveskins** [gopasspw/gopassbridge#160]
After loading this plugin into ungoogle-chromium from source I was getting an error:
   `Access to the specified native messaging host is forbidden.`

The "gopass jsonapi configure" step in set up seemed to have generated a com.justwatch.gopass.json file with the incorrect extention ID in 
```
  "allowed_origins": [
        "chrome-extension://<Here>/"
    ]
```
I fixed this by copying the Gopass Bridge extension ID that is displayed on the chrome://extensions/ page into this file.

**Comment by Pharb** [comment]
Hi @iveskins,

thanks for reporting your setup issue.

Gopass will always set `kkhfnlkhiapbiehimabddjbimfaijdhk` as the chrome-extension ID, which is the extension
This is hard-coded here: [gopass-jsonapi/internal/jsonapi/manifest/manifest.go#L17](https://github.com/gopasspw/gopass/blob/264d139fe52efca1049a96504d84d9e158ef214f/cmd/gopass-jsonapi/internal/jsonapi/manifest/manifest.go#L17)

This is the ID as published on the chrome-web-store: https://chrome.google.com/webstore/detail/gopass-bridge/kkhfnlkhiapbiehimabddjbimfaijdhk 

So far my understanding is that installing the extension for development with "Load unpacked" would not need special setup.
How exactly your you installing the extension? Anything special about your version of Chromium regarding the Chrome Web Store?

**Comment by iveskins** [comment]
Hi, Thanks for following up. This does seem to be a quirk of the version of chrome I was using, as it doesn't connect to the webstore. I will close this issue.
