### ISSUE TITLE
[v1.9.3-rc.0 incompatibility] comand 'gopass jsonapi configure' is not recognized

### ISSUE THREAD

**Issue by glowinthedark** [gopasspw/gopassbridge#163]
Running the command for configuring **gopassbridge** as described at https://github.com/gopasspw/gopass/blob/master/docs/setup.md#filling-in-passwords-from-browser does not produce the expected result:

## Expected:

Running the command shows the configuration options:
```bash
gopass jsonapi configure
```

## Actual:
Running the command above performs a repository search for `jsonapi`.

#### Notes: 
Apparently, either the docs or the lastest `gopass` are out of sync.

**Comment by icyd** [comment]
gopass-jsonapi is a need *binary* by itself now, if you are using the source, after *go build* and *go install*, the command *gopass-jsonapi* is available.

**Comment by glowinthedark** [comment]
@icyd:

I ran:

```bash
go get -u -v github.com/gopasspw/gopass
```

which re-built the latest `gopass`:

```bash
❯ $GOPATH/bin/gopass -v
gopass 1.9.3-git+HEAD go1.14.2 darwin amd64
```
but this did not create the `gopass-jsonapi`:

```
$GOPATH/bin/gopass-jsonapi  -v
zsh: no such file or directory: ~/projects/go/bin/gopass-jsonapi
```

as an alternative I also tried:

```
cd $GOPATH/src/github.com/gopasspw/gopass
go build && go install
rehash
which -a gopass-jsonapi
gopass-jsonapi not found
```

### Extra info

```bash
❯ git remote show origin
* remote origin
  Fetch URL: https://github.com/gopasspw/gopass
  Push  URL: https://github.com/gopasspw/gopass
  HEAD branch: master

❯ git log
commit 11660a16cf76ddef57134163a7c4b0d19ab0fb7d (HEAD -> master, origin/master, origin/HEAD)
Author: Sebastian Kurfürst <sebastian@neos.io>
Date:   Thu Jul 23 13:39:45 2020 +0200

```

**Comment by icyd** [comment]
Glad to here that! Yes, the documentation doesn't reflect this steps, also the *release* binaries, don't contain this command pre-build.

**Comment by icyd** [comment]
If you use the release binary 1.9.2, the command is still available  gopasspw/gopass#1471

**Comment by Pharb** [comment]
Thanks for reporting this upcoming incompatibility. I can confirm that as long as you are using gopass v1.9.2. this will not be an issue.

Of course eventually 1.9.3 will break the current "jsonapi" setup.

To prepare for that we need to solve the "jsonapi configure" calls and how to access the "jsonapi" binary via native messaging for browser interactions.

Any help is very much appreciated.

Particularly one big issue might be if and how we have to maintain a separate "gopass-jsonapi" release binary and putting that into the established package managers most users probably use to install gopass.

**Comment by Pharb** [comment]
FYI: Upgrade steps for upcoming gopass 1.10 release are tracked in https://github.com/gopasspw/gopassbridge/issues/165
