### ISSUE TITLE
Problems with Firefox addon 

### ISSUE THREAD

**Issue by mipimipi** [gopasspw/gopassbridge#173]
Hi,
on my Arch Linux machine gopass 1.10.1 and in the Firefox browser gopass bridge 0.8.0 is installed. I ran `gopass-jsonapi configure`. After all, when I execute the addon (i.e. want it to fill in some credentials on a web site), I get an error message "Please update gopass to version 1.8.5 or newer". Did I miss anything at my end?
Thanks,  mipi

**Comment by micxer** [comment]
Same with Chrome, but different error message: "Error when communicating with the native messaging host." together with telling me to re-setup the integration if I upgraded to gopass v1.10 or newer.

**Comment by Kjir** [comment]
Seems to be related to https://github.com/gopasspw/gopass/issues/1563

**Comment by Pharb** [comment]
Thanks for reporting this issue. The problem with using the Arch package is that the Makefile is using an invalid version format, which is fixed on the latest gopass master, for more details please see this issue: https://github.com/gopasspw/gopassbridge/issues/171

Please make sure you have latest `gopass-jsonapi --version` installed on your system and run `gopass-jsonapi configure` to setup your brower integrations.

In case there are any more specific problems or errors, please open a new issue.
