### ISSUE TITLE
Recent regression: "Please update gopass to version 1.8.5 or newer"

### ISSUE THREAD

**Issue by blinry** [gopasspw/gopassbridge#174]
Since a few weeks, when I click the gopassbridge button in Chromium, it says "Please update gopass to version 1.8.5 or newer". I can search for accounts, and it fills them in as before, but that message is new, and it doesn't auto-suggest accounts for the current domain anymore, as before.

gopassbridge version: 0.8.0
gopass version: 1.10.1
JSON API for Chromium is enabled :)

Let me know if I can help you debug/reproduce this!

**Comment by Airblader** [comment]
See pinned issue #171

**Comment by blinry** [comment]
Ah, thanks, didn't see that! :) Closing this issue, as it is identical to the one you linked to.
