### ISSUE TITLE
Does not work with gopass version 1.10.1

### ISSUE THREAD

**Issue by dzervas** [gopasspw/gopassbridge#176]
I'm not sure if I missed some step but after updating gopassbridge on firefox to 0.8 and gopass to 1.10.1 and execute `gopass-jsonapi config` every time I try to open gopassbridge I get "Upgrade gopass to version 1.8.5 or newer". Did I miss something?

**Comment by donnex** [comment]
Could it be related to https://github.com/gopasspw/gopassbridge/issues/171 ?

**Comment by dzervas** [comment]
Huh! Yes it is! Thank you
