### ISSUE TITLE
Keyboard shortcut doesn't work on Linux - Make it customizable

### ISSUE THREAD

**Issue by freijon** [gopasspw/gopassbridge#185]
On Windows I can successfully execute Ctrl+Shift+U and it shows the Gopass Bridge. However on Linux it inserts an underlined "u" in the entry field.

I think it would be great if we could customize the keyboard shortcut in the settings to our needs.

**Comment by martinhoefling** [comment]
It's documented for chrome and firefox on the main page https://github.com/gopasspw/gopassbridge#change-default-shortcut

**Comment by freijon** [comment]
Indeed, that worked. Thank you!
