### ISSUE TITLE
Copy-Action needs to be used twice when pinentry gets called

### ISSUE THREAD

**Issue by leogott** [gopasspw/gopassbridge#190]
**Steps to reproduce:** Open a new tab, search for an entry in gopassbridge and click copy, satisfy the pinentry and then try to paste the password.
**Expected:** the password was decrypted and is stored in the clipboard.
**Actual:** the clipboard does not contain the password, and I have to search for the entry and click copy a second time.

Apparently gopassbridge doesn't remember to complete the action. It's very annoying, but provided the pgp-agent runs, it doesn't stop me or anything.
This bug has existed for a while, but I always forgot to report it.

Windows 10 + Firefox 85

**Comment by leogott** [comment]
An update: Currently on clicking copy, the pinentry window opens, and then closes again after a very short time.

**Comment by martinhoefling** [comment]
I don't see a technically feasible solution as 

- gopass and not gopassbridge is requesting for the pinentry (via gpg)
- web extensions are closed when focus is lost by clicking on the pinentry
