### ISSUE TITLE
Provide workaround for websites which ask for username, but need email

### ISSUE THREAD

**Issue by leogott** [gopasspw/gopassbridge#196]
Preface: I'l totally accept a "this is out of scope, you're on your own" for this one.

I'm dealing with an authentication service, where several very different login-forms exist, on different sub-domains, and all ask for the same credentials. Except for one, which asks for the email derived from the username.

Ideally I'd use the same secret-file for all of them, and gopassbridge automatically entered the email in this case.

A way I imagine this could work on this specific website, is if gopassbridge matched the id of the input to a field-name in the secret, and I stored the email in this field.

**Comment by martinhoefling** [comment]
I think this would be covered by https://github.com/gopasspw/gopassbridge/issues/34. The jsonapi side part is implemented already but the client / gopassbridge side part is not.

**Comment by martinhoefling** [comment]
@leogott please check and close as duplicate if you feel it's covered by #34

**Comment by leogott** [comment]
It's pretty close. I added a comment with the part I felt was missing.
