### ISSUE TITLE
Auto-fill doesn't happen after pin entry, resulting in extra clicks

### ISSUE THREAD

**Issue by zsau** [gopasspw/gopassbridge#20]
MacOS 10.13.3, Firefox 59.0.2

When I click on an entry in the toolbar drop-down, if my store password isn't currently cached then pinentry-mac pops up (as expected) for me to enter the password. But by the time I hit enter and return to Firefox, gopassbridge seems to have lost track of the fact that I clicked on an entry. So I have to click on the same thing again, which is a bit redundant. It's also extra-annoying for me because I use a YubiKey with touch-to-decrypt, so I have to reach for the device twice (or else wait for it to time out before the second attempt).

**Comment by martinhoefling** [comment]
So this probably happens since defocusing the window closes the tool popup. I'll take a look at what is possible.

**Comment by martinhoefling** [comment]
"When the user clicks anywhere outside the popup, the popup is closed. " from https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups. One potential solution would be to refactor the whole process to use a background script to insert the credentials once clicked on the entry (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/background).

**Comment by martinhoefling** [comment]
Closed with PR #47
