### ISSUE TITLE
Cannot create new passwords from gopass-bridge

### ISSUE THREAD

**Issue by yourealwaysbe** [gopasspw/gopassbridge#201]
When adding a new password, gopassbridge either hangs or fails on clicking "create". When running Firefox from the command line, i see the following message in the terminal:

```
You did not specify a user ID. (you may use "-r")

Current recipients:

Enter the user ID.  End with an empty line: 
```

Creating new passwords with "gopass insert" on the command line works fine. "gopass recipients" lists all intended recipients. I have tried running "gopass-jsonapi configure" a few times. As far as i can tell, i've followed all the gopass, gopass-jsonapi, and gopassbridge setup instructions in full (and again).

**Comment by martinhoefling** [comment]
Seems like missing configuration in gopass. @dominikschulz do you have an idea where that message could come from?
