### ISSUE TITLE
Implementation for MS Edge

### ISSUE THREAD

**Issue by raven2cz** [gopasspw/gopassbridge#203]
Any chance to implement gopassbridge for MS Edge?

**Comment by martinhoefling** [comment]
Im not sure if any of the current developers is using edge or has capacity to test on edge too. Have you tried to install via the chrome web store as mentioned in the [Microsoft Documentation](https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026). If that works, we can document it.

**Comment by brad-jones** [comment]
Just installed gopassbridge into Edge & then used it to login to github. No problems so far. Going to see if Edge really is any faster than Chrome.

**Comment by brad-jones** [comment]
FWIW just over a year later & gopassbridge no longer works in Edge. Not sure if Edge updated something (most likely) or if latest versions of gopass has broken it (unlikely), still working fine in Chrome & Firefox.

Looks like my little Ms Edge experiment is over haha.

![image](https://github.com/gopasspw/gopassbridge/assets/2754772/b6a5346b-9e83-4e15-8cf6-5b8a45a1ee6b)
