### ISSUE TITLE
Documentation for windows

### ISSUE THREAD

**Issue by martinhoefling** [gopasspw/gopassbridge#21]
Test and document gopassbridge usage on windows.

**Comment by Project0** [comment]
Just hadd this problem here: https://github.com/gopasspw/gopass/issues/899

**Comment by martinhoefling** [comment]
@Project0 added documentation to gopass in https://github.com/gopasspw/gopass/pull/904 

Is there anything windows specific that should be added to gopassbridge as well? Please reopen if so.

**Comment by martinhoefling** [comment]
@Project0 added documentation to gopass in https://github.com/gopasspw/gopass/pull/904 

Is there anything windows specific that should be added to gopassbridge as well? Please reopen if so.
