### ISSUE TITLE
When are we creating a new release to the Chrome and Mozilla stores?

### ISSUE THREAD

**Issue by rounakdatta** [gopasspw/gopassbridge#217]
Hello maintainers,
The last release was quite sometime back.
![image](https://user-images.githubusercontent.com/20105014/161395598-f85cf742-63c2-469c-b835-d436d9eea3da.png)

What is the current release plan of the project? Are we not planning to release the latest stable version to the stores?

**Comment by dominikschulz** [comment]
I don't think we have an automated release process for this repo and only one or two persons can actually push a release.

That's something we should change.

**Comment by rounakdatta** [comment]
Thanks! I think @martinhoefling has published a release!

**Comment by martinhoefling** [comment]
Yes, I did.
