### ISSUE TITLE
integration with snap-installed firefox

### ISSUE THREAD

**Issue by anotherthomas** [gopasspw/gopassbridge#220]
Ubuntu 22.04. installs firefox as snap, and I wasn't able to integrate the gopass bridge with a firefox running this way. Are there any solutions/workarounds/other to make that work again?

**Comment by martinhoefling** [comment]
https://forum.snapcraft.io/t/native-messaging-support-in-strictly-confined-browser-snaps/26849

Seems like this is a problem with native messaging in general an gopassbridge cannot do anything here.
