### ISSUE TITLE
Chrome Extension settings pop-up unusable: it shakes

### ISSUE THREAD

**Issue by pavel-kolesnikov** [gopasspw/gopassbridge#221]
I've installed the Chrome Extension and trying to open the settings of the extension by the link in extension page in the browser.
Exactly this link: chrome://extensions/?options=kkhfnlkhiapbiehimabddjbimfaijdhk

What I see is:
https://user-images.githubusercontent.com/170665/165572005-3da5ae53-7525-48b0-b149-2a7a3443d775.mp4

Can't make it stop, the Settings are unusable...

**Comment by martinhoefling** [comment]
I cannot reproduce the issue (tried with different sizes). Can you provide a little bit more information what browser version, operating system etc.?

**Comment by pavel-kolesnikov** [comment]
Let's hope none else affected.
