### ISSUE TITLE
Improve search error handling and test coverage

### ISSUE THREAD

**Issue by Pharb** [gopasspw/gopassbridge#45]
I suspect there are some bugs related to the spinner getting stuck and errors sometimes not being displayed, e.g. when gopass is not properly setup.

Also test coverage of `search.js` is pretty low.

**Comment by martinhoefling** [comment]
Thx, I recently added coverage to most parts and refactored out some parts of search.js Search is the last uncovered part so I would definitely like to see this gap closed before the next release and I am happy if you wanna work on it.

**Comment by martinhoefling** [comment]
@Pharb, are you working on it? We can do this after #47 is merged or implement the tests together with #47.

**Comment by Pharb** [comment]
Yes, I'll continue with it now that the other PRs are merged.

**Comment by Pharb** [comment]
Some of the error cases and spinner handling might have changed with #63.
