### ISSUE TITLE
Add the ability to trigger notifications from gopassbridge

### ISSUE THREAD

**Issue by Pharb** [gopasspw/gopassbridge#48]
Include user setting.

Should the default be "on" or "off"? @martinhoefling 

If we keep the notification usage minimal (only for edge cases in error handling as described in #47, I would set it to "on", ok?

**Comment by martinhoefling** [comment]
We can use it as default for errors, no?

**Comment by Pharb** [comment]
I think the UX would be pretty bad to show every error as a notification.
For direct user interactions like searching in the popup, I would much prefer a direct inline error message.

**Comment by martinhoefling** [comment]
Agreed.
