### ISSUE TITLE
Move clipboard handling to gopass jsonapi

### ISSUE THREAD

**Issue by Pharb** [gopasspw/gopassbridge#49]
Add clipboard handling to gopass jsonapi and use it.

This avoids the workaround we currently have to do to use the browser clipboard functionality, which is much more restricted and cannot be used from e.g. background scripts, see discussion in #47.

This also has the benefit of native gopass clipboard functionality, like automatically clearing it after a certain amount of time.

**Comment by martinhoefling** [comment]
This must work with all entries and not just passwords though. Still unsure if it is better to leave it in the browser plugin.

**Comment by Pharb** [comment]
@martinhoefling You probably mean copying other attributes to clipboard as in #23?

gopass supports writing any key of a structured YAML secret to clipboard, not just the password, e.g. `gopass show Account/github.com --clip`.
It should therefore be possible to trigger the same via the jsonapi?

**Comment by martinhoefling** [comment]
Works like a charm! Yeah, so we need to create a separate message in gopass that supports sub keys and can implement this.

**Comment by zsau** [comment]
Is there an issue that's tracking the gopass side of this? I couldn't find one, but may have just missed it.

**Comment by martinhoefling** [comment]
https://github.com/gopasspw/gopass/releases/tag/v1.8.5 has been released with gopass api changes

**Comment by Pharb** [comment]
This should now be safe to implement as we tell users to update to 1.8.5 or newer with the next gopassbridge release: https://github.com/gopasspw/gopassbridge/pull/117

**Comment by kristiankostadinov** [comment]
I think the api needs another extension in order to support copying via a path selector. 
The plugin currently allows copying nested values and list items, whereas the api doesn't.

Assuming I have the following secret
```
password
---
url: testsite.com
username: testusername
nested:
  value: some-value
anothernested:
  value: another-value
array:
  - one
  - two
```
I wouldn't be able to copy `array[0]` or `nested.value`/`anothernested.value`.

**Comment by Pharb** [comment]
@kristiankostadinov Good catch. 👍 

I think the first iteration when implementing this feature could be to use the current API to copy the password to clipboard, which should already bring some improvements.

Another next step for this enhancement would be an improved API to handle arbitrary items from the YAML data. Not sure here what the simplest approach would be for that, so any proposals for that are welcome.

**Comment by kristiankostadinov** [comment]
I was thinking of extending the yaml secret [value getter ](https://github.com/gopasspw/gopass/blob/e5dfaa747e34e384b9301257af5635a68c4969e6/pkg/store/secret/yaml.go#L26) and using the jq/[yq](https://mikefarah.gitbook.io/yq/commands/read#basic) format for the path expression (`array.[0]`/`nested.value`). 
Seems like the least invasive way and would work for `show` with a path as well.

**Comment by Pharb** [comment]
@kristiankostadinov Yes, that would be a good approach. We shouldn't re-invent the wheel here.

Can parts of yq be included as a go library in gopass?

**Comment by Pharb** [comment]
@kristiankostadinov About the yq syntax, we should not worry about this now. Gopass might rework/remove the YAML support and it is probably a waste of time to implement a more complicated query syntax.

**Comment by martinhoefling** [comment]
@Pharb @kristiankostadinov , with the suggestion to not move on with yaml support on gopass side, is there still an open part of the issue?

**Comment by Pharb** [comment]
I think we are good here for now. We can keep the YAML support like it is and when gopass removes it, we can cleanup the old clipboard handling code.

Thanks for the help again @kristiankostadinov , please let me know if I missed anything 🙂
