### ISSUE TITLE
No result when opening popup

### ISSUE THREAD

**Issue by Pharb** [gopasspw/gopassbridge#66]
Trying to login with v0.3.0 on github.com/login works fine.

The version from the current master does not work, it just shows "no results for github.com" when opening the popup. This affects both Chrome and Firefox.

This is probably a blocker for releasing 0.4.

**Comment by martinhoefling** [comment]
Seems like a bug in gopass (tested with test-client.go in repo)

```
$ echo '{"type":"queryHost","query":"github.com"}' | ./test-client | gopass jsonapi listen

[]
```

**Comment by martinhoefling** [comment]
It's actually an invalid message sent by gopassbridge. I'll push a fix asap.
