### ISSUE TITLE
Automatic push to git remote fails

### ISSUE THREAD

**Issue by speedmann** [gopasspw/gopassbridge#79]
When trying to add a new login with chrome Extension of gopassbridge, i get the following error
`failed to store secret: failed to push to git remote: exit status 128`

The enty is successfully created and committed, but not pushed to git.

Doing a `gopass create` successfully pushes the newly created entry (and any previously created entries with gopassbridge).
I suspect the issue to be somewhere in the Extension, but have no idea where to look for more details

Gopassbridge Version: 0.4.0
Gopass version: gopass 1.8.2 (10b7d6f172a8a99f9d8176a45b847b16b622bc04 2018-06-29 07:39:27) go1.10.3 darwin amd64
git version 2.16.2
OS: macOS 10.13.6

**Comment by speedmann** [comment]
Hello Martin, thank you for this tipp. I Am using ssh together with the gpg agent which most probably not started when the wrapper script is running...

**Comment by martinhoefling** [comment]
@speedmann did that solve your issue?

**Comment by Pharb** [comment]
@speedmann I'll assume that this issue is resolved.
If you need more help, feel free to reopen this issue are create a new one.
