### ISSUE TITLE
Support displaying `gopass otp` code if `totp` field is in data

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopassbridge#87]
Filing this separate from https://github.com/gopasspw/gopassbridge/issues/34 since this doesn't relate to xpath, etc, and is data the extension might not have access to (since it's a derived value rather than from the plaintext data, not sure what `gopassbridge` receives).

It'd be nice to see the current OTP token when the full text is visible.

Any pointers? I would be interested in adding this.

**Comment by Pharb** [comment]
Thank you for the suggestion. I'm not using the OTP feature of gopass myself, but that sounds like a helpful addition to show the generated token in the gopassbridge popup.

To see what data gopassbridge receives from gopass you can take a look at these files:
- this is the `jsonapi` that gopassbridge uses to communicate with gopass: https://github.com/gopasspw/gopass/blob/master/pkg/jsonapi/responses.go#L22
- the `getData` message is used to get all data for the detail view in gopassbridge: https://github.com/gopasspw/gopassbridge/blob/master/web-extension/details.js#L3 

It looks like a minor restructuring of the code here would be necessary to avoid duplication within gopass: https://github.com/gopasspw/gopass/blob/master/pkg/action/otp.go#L23

For extending the `jsonapi` I see two options:
1) Create a new API message like `getOtpToken` that only returns the OTP token on demand.
This would probably require more complexity in gopassbridge to handle additional API calls.
2) Extend the `getData` message response to always include the current OTP token.
This might make it easier for gopassbridge to figure out if a OPT is actually configured for a certain domain and only then render the token field. This would also be easier for API backwards compatibility as the absence of the response OTP token could also just hide the token field in the UI.

Personally I think option 2) sounds easier to implement.

If you need any more help, feel free to just ask here.

You can also open a work-in-progress pull request if you want early feedback on your contribution.

**Comment by colemickens** [comment]
Alright, since I had to read through all of this source to figure out why Windows wasn't working (turns out the release was too old)... I realized how straight forward this is, especially with your pointers. (Thanks!)

I guess there's three options I see:
1. Add `getOtpCode`. Requires most work in the extension.
2. Add a new field to the `getDataMessage` struct. Requires reading an extra json field and adding a new DIV in the extension, less work, but still requires me figuring out local extension dev...
3. Just stick the string `"\n" + "current totp code: " + totpCode` on the end of `Entry`. No extension change required.

#3 is easiest, but not my favorite, especially since I'm not sure what the UX would end up looking like (does the extension strip off "current totp code:" when the user clicks that field to copy it?)

Let me know which one I should add. For now I'll add 3 since it's the bare minimum.

**Comment by colemickens** [comment]
Ah, never mind, it looks like there's just one way that makes obvious sense, and it works well with the extension UX as-is! Very nice, no modifications to the extension needed: https://github.com/gopasspw/gopass/pull/975

**Comment by colemickens** [comment]
This is merged into `gopass`. I'm going to go ahead and close this. Thanks again.

**Comment by martinhoefling** [comment]
Thx @colemickens
