### ISSUE TITLE
Allow User / Password auto-filling for basic auth

### ISSUE THREAD

**Issue by xschlef** [gopasspw/gopassbridge#89]
Hi,

when Firefox prompts for basic auth credentials, I have no chance of using gopass bridge without resorting to hotkeys. Maybe allow automatic filling of basic auth prompts?

I have no idea if this is possible.

Thanks!

**Comment by martinhoefling** [comment]
Don’t think that this can be done programmatically. However, if you store the url like:

`url: https://myuser:mypass@example.com` it might be possible. The url then needs to be opened via blank tab + gopass search.

**Comment by xschlef** [comment]
Thanks!

**Comment by Pharb** [comment]
It might be possible that this can be implemented, see #91 for details.
