### ISSUE TITLE
Support for BasicAuth

### ISSUE THREAD

**Issue by jerger** [gopasspw/gopassbridge#91]
As some of the webapps I use are using BasicAuth. Support of BasicAuth credentials comparable to passff would be great :-)

**Comment by martinhoefling** [comment]
If somebody wants to implement https://github.com/passff/passff/commit/97c37cf37c5a7a7b4da0c62c7fdd448973c28244 feel free to get in touch.

**Comment by jerger** [comment]
Will spend some money for implementation ... as I'm not the js guru myself :-)
pls. contact buero@meissa-gmbh.de if someone is willing to support ...

**Comment by jerger** [comment]
Thanx for your work :-)
Will try out your Solution it in the upcoming year, contribute myself some code to the world & increase donations to fsf :-)

**Comment by jerger** [comment]
Works like a charm :-)

![bildschirmfoto_2019-01-25_15-46-15](https://user-images.githubusercontent.com/2706174/51752760-8c370c80-20b8-11e9-9194-a278da89ed99.png)
