### ISSUE TITLE
Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopassbridge#93]
I'm not sure why I get this error sometimes. The extension seems to still be working in reality. I can see the notes, I can click the clipboard and get my password. But if I click the entry, it fails to fill and gives the message: "Could not establish connection. Receiving end does not exist."

This seems to continue until I restart Firefox.

**Comment by martinhoefling** [comment]
@colemickens can you still reproduce the issue? Is it only happening on first invocation? Here, I have a similar problem since unlocking my gpg key via keychain makes the first request after booting/login to the system fail.

**Comment by martinhoefling** [comment]
I think this is when you try to open the popup and it tries to mark the login fields, e.g. in an empty page or a non http/https page, like extensions:// about etc.

**Comment by lockejan** [comment]
Hi, I encounter the exact same behaviour but in Chromium.

Chormium Version "89.0.4389.90 (Official Build) Arch Linux (64-bit)"
gopass-jsonapi: 1.11.1
gopass 1.12.4 (2021-03-21 11:02:13) go1.16.2 linux amd64

The dev-tools aren't given me any output on that.
Any suggestions how this can be further tracked down?

It happened after resuming from suspend. I had to unlock my keychain first, but it failed as described.
