### ISSUE TITLE
No result in popup when auto search

### ISSUE THREAD

**Issue by lyze237** [gopasspw/gopassbridge#94]
Hello!

When I click on the browser plugin, it can't find results.

![2018-12-11_10-20-45](https://user-images.githubusercontent.com/11274700/49790469-91214600-fd2e-11e8-9f19-92ced1a3e9a8.png)

However when I search for the same thing it works just fine.

![2018-12-11_10-20-39](https://user-images.githubusercontent.com/11274700/49790467-8f578280-fd2e-11e8-9a31-47be95bc6c1b.png)

specs:
* gopass 1.8.3 (97ac44d93e48d378bfbb80180c54f76a8b1a5cef) go1.11.2 windows amd64
* chrome
* latest addon

**Comment by martinhoefling** [comment]
It's a windows issue on the gopass side. Gopassbridge sends a query host message and does not get the entries in return due to the separators. The issue is https://github.com/gopasspw/gopass/issues/982 as far as I remember.
